name: gen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # see
    # https://github.com/actions/virtual-environments/issues/3316
#   - name: Setup path
#     shell: cmd
#     run: |
#       echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
    - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "12.0.0"
        forceVersion: true
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Install bindgen
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: bindgen

    - name: Generate
      shell: cmd
      run: |
        #set PATH=C:\msys64\mingw64\bin;%PATH%
        bindgen ./header.h -o binding.rs

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
# vim: set ts=2 sts=2 sw=2:
